apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pm-back-pv
  namespace: pm-platform
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage-0"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi