apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: back-pm2
  labels:
    bdmd.com/service: back-pm2
spec:
  replicas: 1
  selector:
    matchLabels:
      bdmd.com/service: back-pm2
  template:
    metadata:
      labels:
        bdmd.com/service: back-pm2
    spec:
      containers:
        - name: svc
          image: dockerdist.bdmd.com/project-manage:20190617_112707
          ports:
            - name: back-pm2
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: "/pm-data/"
              name: back-pm2-pvc
      volumes:
        - name: back-pm2-pvc
          persistentVolumeClaim:
            claimName: pm-back-pv
